const express = require("express");
const router = express.Router();
const multer = require("multer");
const { v4: uuidv4 } = require("uuid");
const fs = require("fs");
const PDFDocument = require("pdfkit");
const DataFile = require("../models/DataFile");

// storage config
const storage = multer.diskStorage({
  destination: "uploads/",
  filename: (req, file, cb) => {
    cb(null, uuidv4() + ".json");
  }
});

const upload = multer({ storage });

function flattenObject(obj, prefix = "") {
  if (obj === null || obj === undefined) {
    return [{ key: prefix || "value", value: "-" }];
  }

  if (typeof obj !== "object") {
    return [{ key: prefix || "value", value: String(obj) }];
  }

  const entries = [];
  const isArray = Array.isArray(obj);

  Object.entries(obj).forEach(([key, value]) => {
    const compositeKey = prefix
      ? isArray
        ? `${prefix}[${key}]`
        : `${prefix}.${key}`
      : key;

    if (value !== null && typeof value === "object") {
      entries.push(...flattenObject(value, compositeKey));
    } else {
      entries.push({
        key: compositeKey,
        value: value === undefined || value === null ? "-" : String(value)
      });
    }
  });

  return entries;
}

function drawTableHeader(doc, y) {
  doc
    .save()
    .roundedRect(50, y, 500, 28, 6)
    .fill("#E2E8F0")
    .restore();

  doc
    .fillColor("#1E293B")
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("Key", 65, y + 8, { width: 170 })
    .text("Value", 255, y + 8, { width: 280 });

  return y + 38;
}

/*
API 1 - Upload JSON File
*/
router.post("/upload", upload.single("file"), async (req, res) => {
  try {
    const jsonData = JSON.parse(fs.readFileSync(req.file.path, "utf8"));

    const newFile = new DataFile({
      filename: req.file.filename,
      filepath: req.file.path,
      data: jsonData,
      fileSize: req.file.size
    });

    await newFile.save();
    res.json({ message: "File uploaded successfully" });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

/*
API 2 - Get All Files
*/
router.get("/", async (req, res) => {
  const files = await DataFile.find().sort({ uploadDate: -1 });
  res.json(files);
});

/*
API 3 - Download File as PDF Report
*/
router.get("/download/:id", async (req, res) => {
  try {
    const file = await DataFile.findById(req.params.id);

    if (!file) {
      return res.status(404).json({ error: "File not found" });
    }

    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const rows = flattenObject(file.data);

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="MachineData_${file._id}.pdf"`);

    doc.pipe(res);

    const gradient = doc.linearGradient(0, 0, doc.page.width, 0);
    gradient.stop(0, "#4F46E5").stop(1, "#9333EA");

    doc.rect(0, 0, doc.page.width, 110).fill(gradient);

    doc
      .fillColor("#FFFFFF")
      .font("Helvetica-Bold")
      .fontSize(24)
      .text("Machine Data Report", 50, 34)
      .font("Helvetica")
      .fontSize(11)
      .text(`Upload Date: ${new Date(file.uploadDate).toLocaleString()}`, 50, 72);

    let y = 140;
    y = drawTableHeader(doc, y);

    rows.forEach((row) => {
      if (y > doc.page.height - 90) {
        doc.addPage();
        y = 60;
        y = drawTableHeader(doc, y);
      }

      doc
        .font("Helvetica")
        .fontSize(10)
        .fillColor("#334155")
        .text(row.key || "-", 65, y, { width: 170 })
        .fillColor("#0F172A")
        .text(row.value || "-", 255, y, { width: 280 });

      doc
        .moveTo(50, y + 16)
        .lineTo(550, y + 16)
        .lineWidth(0.4)
        .strokeColor("#CBD5E1")
        .stroke();

      y += 22;
    });

    doc
      .font("Helvetica-Oblique")
      .fontSize(10)
      .fillColor("#475569")
      .text("Generated by Machine Data Dashboard", 50, doc.page.height - 40, {
        align: "center",
        width: doc.page.width - 100
      });

    doc.end();
  } catch (error) {
    console.error("PDF generation failed:", error);
    res.status(500).json({ error: "Failed to generate PDF" });
  }
});

/*
API 4 - Stats
*/
router.get("/stats/summary", async (req, res) => {
  const totalFiles = await DataFile.countDocuments();
  const totalSize = await DataFile.aggregate([
    { $group: { _id: null, total: { $sum: "$fileSize" } } }
  ]);

  res.json({
    totalFiles,
    totalSize: totalSize[0]?.total || 0
  });
});

module.exports = router;

